apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example
  namespace: example
spec:
  gateways:
    - mesh
  hosts:
    - www.example.com
    - example.com
  http:
    - match:
      - headers:
          x-custom-header:
            exact: ok
          x-prefix-header:
            prefix: start
      route:
        - destination:
            host: has-header
    - match:
        - headers:
            x-custom-header: {}
      route:
        - destination:
            host: has-present-header
    - match:
      route:
        - destination:
            host: default
